const STORE='pals_pwa_v2';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const state=Object.assign({weight:'',age:'',rhythm:'nonshock',timer:0,running:false,events:[],evaluation:'',interventions:'',response:'',postrosc:'',reaction:'',description:'',analysis:'',actions:'',noteTitle:'',freeNotes:'',checks:{}},JSON.parse(localStorage.getItem(STORE)||'{}'));
let timerId=null,recognition=null,deferredPrompt=null;
const save=()=>{localStorage.setItem(STORE,JSON.stringify({...state,running:false})); const el=$('#saveStatus'); if(el){el.textContent='Guardado automático'; setTimeout(()=>el.textContent='Guardado local activo',700)}};
const fmtTime=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function doseData(w){if(!w||w<=0)return[]; const r=(n,d=2)=>Number(n.toFixed(d)); return [
['Epinefrina IV/IO',`${r(.01*w)} mg`,'Cada 3–5 min; verificar concentración'],
['Amiodarona',`${r(5*w,1)} mg`,'En FV/TV refractaria; verificar máximo'],
['Lidocaína',`${r(1*w,1)} mg`,'Alternativa según protocolo'],
['Adenosina 1ª',`${r(Math.min(.1*w,6),1)} mg`,'Bolo rápido'],
['Adenosina 2ª',`${r(Math.min(.2*w,12),1)} mg`,'Bolo rápido'],
['Atropina',`${r(Math.max(.1,Math.min(.02*w,1)),2)} mg`,'Verificar mínimo/máximo'],
['Cardioversión',`${r(.5*w,1)}–${r(1*w,1)} J`,'Aumentar a 2 J/kg si persiste'],
['Desfibrilación',`${r(2*w,1)} J → ${r(4*w,1)} J`,'Posteriores ≥4 J/kg según protocolo'],
['Cristaloide',`${r(10*w,0)}–${r(20*w,0)} mL`,'Reevaluar tras cada bolo']];}
const algorithms={nonshock:['RCP de alta calidad y ventilación eficaz.','Epinefrina precoz y repetir cada 3–5 min.','Reevaluar ritmo cada 2 min; no desfibrilar.','Buscar y tratar causas reversibles.'],shock:['RCP de alta calidad y desfibrilación temprana.','Reanudar RCP inmediatamente después de cada descarga.','Epinefrina después de la segunda descarga según algoritmo.','Considerar antiarrítmico si FV/TV persiste.'],brady:['Oxigenar y ventilar; identificar causa.','Si FC <60/min con mala perfusión pese a ventilación, iniciar RCP.','Epinefrina; atropina si aumento vagal/BAV.','Considerar marcapaseo en bloqueo avanzado.'],svt:['Valorar estabilidad hemodinámica.','Maniobras vagales si estable.','Adenosina rápida si QRS estrecho regular.','Cardioversión sincronizada si inestable.']};
const scenarios=[
{id:'fv',title:'FV/TV sin pulso en adolescente',weight:50,age:15,rhythm:'shock',intro:'Adolescente con colapso súbito, sin pulso y ritmo desfibrilable.',evaluation:'Paciente inconsciente, apnea y ausencia de pulso; monitor muestra FV.',interventions:'Iniciar RCP, desfibrilar, acceso IV/IO y seguir algoritmo de paro desfibrilable.'},
{id:'aesp',title:'AESP por hipoxia en lactante',weight:8,age:.6,rhythm:'nonshock',intro:'Lactante con deterioro respiratorio que progresa a AESP.',evaluation:'Apnea, cianosis, ausencia de pulso y actividad eléctrica organizada.',interventions:'Ventilación eficaz, RCP, epinefrina precoz y corrección de hipoxia.'},
{id:'brady',title:'Bradicardia sintomática en escolar',weight:25,age:8,rhythm:'brady',intro:'Escolar con bradicardia, hipotensión y mala perfusión.',evaluation:'FC <60/min, alteración del estado mental y pulsos débiles.',interventions:'Oxigenación, ventilación, RCP si persiste mala perfusión y tratamiento etiológico.'},
{id:'svt',title:'TSV inestable en preescolar',weight:18,age:4,rhythm:'svt',intro:'Taquicardia regular de QRS estrecho con hipotensión.',evaluation:'Palidez, llenado capilar prolongado y taquicardia sostenida.',interventions:'Preparar cardioversión sincronizada y sedación si no retrasa el procedimiento.'}];
const checklist=['Asignar líder y roles','Confirmar RCP de alta calidad','Conectar monitor/desfibrilador','Obtener acceso IV/IO','Registrar tiempos y medicamentos','Buscar causas reversibles','Planear cuidados post-ROSC','Realizar debriefing'];
function renderCalc(){const w=parseFloat(state.weight); $('#doseCards').innerHTML=w?doseData(w).map(([a,b,c])=>`<div class="dose"><strong>${a}</strong><span>${b}</span><small>${c}</small></div>`).join(''):'<p class="muted">Capture el peso para calcular.</p>'; $('#algorithmList').innerHTML=algorithms[state.rhythm].map(x=>`<li>${x}</li>`).join('');}
function renderEvents(){ $('#timer').textContent=fmtTime(state.timer); $('#eventLog').innerHTML=state.events.slice().reverse().map(e=>`<div class="event-item">${e}</div>`).join('')||'<p class="muted">Sin eventos registrados.</p>'; $('#timerBtn').textContent=state.running?'Pausar':'Iniciar';}
function addEvent(text){state.events.push(`${fmtTime(state.timer)} · ${text}`); save(); renderEvents();}
function bindState(id,key= id){const el=$('#'+id); if(!el)return; el.value=state[key]??''; el.addEventListener('input',()=>{state[key]=el.value; save(); if(id==='weight'||id==='rhythm')renderCalc();});}
function setupTabs(){$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active')); $$('.panel').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $('#'+b.dataset.tab).classList.add('active');}));}
function setupChecklist(){const root=$('#megaChecklist'); root.innerHTML=checklist.map((x,i)=>`<label><input type="checkbox" data-mega="${i}"> ${x}</label>`).join(''); $$('[data-mega]').forEach(x=>{x.checked=!!state.checks['mega'+x.dataset.mega]; x.onchange=()=>{state.checks['mega'+x.dataset.mega]=x.checked;save();};}); $$('[data-save]').forEach(x=>{x.checked=!!state.checks[x.dataset.save]; x.onchange=()=>{state.checks[x.dataset.save]=x.checked;save();};});}
function setupScenario(){const s=$('#scenario'); s.innerHTML=scenarios.map(x=>`<option value="${x.id}">${x.title}</option>`).join(''); $('#loadScenario').onclick=()=>{const c=scenarios.find(x=>x.id===s.value); Object.assign(state,{weight:String(c.weight),age:String(c.age),rhythm:c.rhythm,evaluation:c.evaluation,interventions:c.interventions,response:'',postrosc:'',timer:0,events:[]}); ['weight','age','rhythm','evaluation','interventions','response','postrosc'].forEach(id=>$('#'+id).value=state[id]); $('#scenarioIntro').textContent=c.intro; save();renderCalc();renderEvents();}; $('#scenarioIntro').textContent=scenarios[0].intro;}
function setupTimer(){ $('#timerBtn').onclick=()=>{state.running=!state.running;if(state.running){timerId=setInterval(()=>{state.timer++;if(state.timer%120===0)addEvent('Ciclo de 2 minutos completado');renderEvents();},1000)}else clearInterval(timerId);save();renderEvents();}; $('#cycleBtn').onclick=()=>addEvent('Ciclo de RCP registrado'); $('#epiBtn').onclick=()=>addEvent('Epinefrina registrada');}
function setupDictation(){$$('.dictate').forEach(btn=>btn.onclick=()=>{const target=$('#'+btn.dataset.target); const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('El dictado no está disponible en este navegador.');return;} if(recognition){recognition.stop();recognition=null;btn.textContent='🎙 Dictar';return;} recognition=new SR();recognition.lang='es-MX';recognition.continuous=true;recognition.interimResults=false;btn.textContent='Detener';recognition.onresult=e=>{const text=[...e.results].slice(e.resultIndex).map(r=>r[0].transcript).join(' ');target.value+=(target.value?' ':'')+text;state[btn.dataset.target]=target.value;save();};recognition.onend=()=>{recognition=null;btn.textContent='🎙 Dictar';};recognition.onerror=()=>{recognition=null;btn.textContent='🎙 Dictar';};recognition.start();});}
function setupDebrief(){ $('#generateDebrief').onclick=()=>{const parts=[['Reacción',state.reaction],['Descripción',state.description],['Análisis',state.analysis],['Acciones',state.actions]].filter(x=>x[1]); $('#debriefOutput').innerHTML=parts.length?parts.map(([h,t])=>`<h3>${h}</h3><p>${t}</p>`).join(''):'<p class="muted">Complete al menos un campo.</p>';};}
function setupNotes(){ $('#copyNotes').onclick=async()=>{await navigator.clipboard.writeText(`${state.noteTitle}\n\n${state.freeNotes}`);}; $('#downloadNotes').onclick=()=>{const blob=new Blob([`${state.noteTitle}\n\n${state.freeNotes}`],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(state.noteTitle||'nota-pals')+'.txt';a.click();URL.revokeObjectURL(a.href);}; $('#clearData').onclick=()=>{if(confirm('¿Borrar todos los datos guardados en este dispositivo?')){localStorage.removeItem(STORE);location.reload();}};}
function setupInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false;});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true;};}
function setupOffline(){const update=()=>{$('#offlineStatus').textContent=navigator.onLine?'En línea':'Sin conexión'};addEventListener('online',update);addEventListener('offline',update);update();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');}
function init(){setupTabs();setupChecklist();setupScenario();setupTimer();setupDictation();setupDebrief();setupNotes();setupInstall();setupOffline();['weight','age','rhythm','evaluation','interventions','response','postrosc','reaction','description','analysis','actions','noteTitle','freeNotes'].forEach(id=>bindState(id));renderCalc();renderEvents();}
document.addEventListener('DOMContentLoaded',init);